# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the company', max_length=100, verbose_name='Company Name')),
                ('employee_count', models.IntegerField(help_text='Total Employees in the company', verbose_name='Employee Count')),
                ('score', models.IntegerField(blank=True, default=0)),
                ('final_rank', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='RankingCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the Ranking Company', max_length=100, verbose_name='Ranking Company Name')),
                ('source', models.CharField(default='Anonymous', max_length=200, verbose_name='Source of Data')),
                ('count', models.IntegerField(help_text='Equal to lowest company ranked.', verbose_name='Number of Companies Ranked')),
                ('companies', models.ManyToManyField(through='Company.CompanyRanking', to='Company.Company')),
            ],
        ),
        migrations.AddField(
            model_name='companyranking',
            name='rankingCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.RankingCompany'),
        ),
    ]
