# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_count', models.IntegerField()),
                ('score', models.IntegerField()),
                ('final_rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='RankingCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=200)),
                ('Number of Companies Ranked', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='companyranking',
            name='rankingCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.RankingCompany'),
        ),
    ]
