# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankingcompany',
            old_name='Number of Companies Ranked',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='companyranking',
            name='rank',
        ),
        migrations.AddField(
            model_name='companyranking',
            name='date_recorded',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rankingcompany',
            name='company_score',
            field=models.ManyToManyField(through='Company.CompanyRanking', to='Company.Company'),
        ),
    ]
