# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20171008_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankingcompany',
            old_name='company_score',
            new_name='merger',
        ),
        migrations.RemoveField(
            model_name='companyranking',
            name='date_recorded',
        ),
        migrations.AddField(
            model_name='companyranking',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
