# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_auto_20171008_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingcompany',
            name='date',
        ),
    ]
