# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_remove_rankingcompany_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankingcompany',
            old_name='merger',
            new_name='companies',
        ),
    ]
